### ISSUE TITLE
New updater checklist

### ISSUE THREAD

**Issue by LouisCAD** [jmfayard/refreshVersions#134]
- [x] Serialize the repositories from `buildSrc` and `Settings` to use them to get versions.
- [x] Automatically use the most stable version if a placeholder isn't resolved.
- [x] Update or remove the Gradle extension so there's no longer ignored configuration.
- [x] Add empty line after each version property
- [x] Make `maven-metadata.xml` files download parallel (coroutines + `Dispatchers.IO`?).
- [x] Make parsing of the files parallel (coroutines + `Dispatchers.Default`?).
- [x] Report hardcoded & dynamic versions (#126)
- [x] New versions sorting strategy #153 
- [x] Show user-friendly error messages when unable to find available versions of an artifact from the given repositories.
- [x] Ease adding dependencies (#125)
- [x] Support cancellation for in-flight network requests.
- [x] Support update of the plugin itself
- [x] Support advertising Gradle update, link to migration guide and write the commands to update the wrapper ([API here](https://services.gradle.org/versions/)).
- [x] Keep user comments added above a property
- [ ] Specify behavior for unused version entries (remove as before by default? add unused metadata comment?)
- [ ] Allow setting minimum stability level for version property (via a comment above it)
- [ ] Allow setting minimum version, via a comment above it (use-case: waiting for that bugfix release to upgrade)
- [ ] Allow overriding filtering & sorting mode per version property (via a comment above it)
- [ ] Allow disabling updates for a version property (via a comment above it)

**Comment by jmfayard** [comment]
Can be considered as done, we have now a way to configure the plugin via `settings { } `

**Comment by LouisCAD** [comment]
There's items left in the checklist, so the issue overall is still relevant and is part of the 1.0.0 milestone.

I need to keep it open to not miss the things that remain to be done.
