### ISSUE TITLE
Dependencies constants plugin checklist

### ISSUE THREAD

**Issue by LouisCAD** [jmfayard/refreshVersions#138]
Provided dependencies constants
- [x] Replace AndroidX Ui dependencies with AndroidX Compose ones.
- [x] Add `Android` object inside `Google` object for Material and other `com.google.android...` libraries.
- [x] Add remaining Google dependencies (AR Core, Play Services, Play Core, Firebase, WearOS)
- [x] Add Android browser helper: https://github.com/GoogleChrome/android-browser-helper
- [x] Add [Coil](https://github.com/coil-kt/coil)
- [ ] Add Beepiz dependencies ([BleGattCoroutines](https://github.com/Beepiz/BleGattCoroutines))
- [x] Add more Jake Wharton dependencies (picnic? others?)
- [x] Add missing kotlinx dependencies (serialization, immutable collections)
- [x] Add ktor client and ktor server
- [x] New kotlinx.serialization dependencies (https://bintray.com/kotlin/kotlinx/kotlinx.serialization.runtime)
- [ ] Double check ktor dependencies against [bintray repo](https://bintray.com/version/files/kotlin/ktor/ktor/1.3.0?order=asc&sort=name&basePath=io%2Fktor&tab=files), and [official artifacts page](https://ktor.io/quickstart/artifacts.html) once it is updated.
- [ ] Add koin
- [x] Add AndroidX libs released with Android 11 beta
- [ ] Link changelogs and release notes pages in KDoc.

Plugin features
- [x] Move it from Splitties to this project
- [x] Explore and decide how to handle BoM versions (maybe another version placeholder flagging BoM allowance might do?)
- [x] Explore auto-adding dependency from Gradle settings (via `gradle` instance?) or buildSrc for the easiest configuration possible

Test improvements:
- [ ] Check all constants are correctly formatted maven coordinates with a supported version placeholder (`_` only for now).
- [ ] Add a test to verify all constants's artifacts can be found in `mavenCentral`, `google`, `jcenter` or `gradlePluginPortal`. (jitpack.io is not supported because of builds reproducibility concerns, write it somewhere for future contributors).

**Comment by jmfayard** [comment]
Move it from Splitties to this project
==> https://github.com/jmfayard/gradle-dependencies-plugins/pull/139

**Comment by LouisCAD** [comment]
Here's where we can see whether AndroidX library groups are using the same version or not by looking at the `requireSameVersion` flag (enabled by default): https://android-review.googlesource.com/c/platform/frameworks/support/+/1206056/12/buildSrc/src/main/kotlin/androidx/build/LibraryGroups.kt

**Comment by jmfayard** [comment]
Largely done, a new ticket is available here
https://github.com/jmfayard/refreshVersions/issues/238

**Comment by LouisCAD** [comment]
Mostly done, yes, though still several things to do.

I'm keeping it pinned for now as a reference and to not forget to address the remaining points soon (for next release ideally).
